### ISSUE TITLE
Use cached binary when running tests on branches other than master

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/build-nargo#18]
### Problem

Running the test suite currently takes ~13 minutes due to having to compile nargo from scratch. This can be quite a long time when testing changes to the test suite when the actual nargo codebase hasn't changed from commit to commit.

### Proposed solution

We should update the github actions to use a prebuilt nargo binary (either the latest nightly build or the uploaded artifact for the noir commit which we would otherwise compile)

**Comment by TomAFrench** [comment]
This'll be much easier once nix builds are here so might as well wait for that.

**Comment by kevaundray** [comment]
Now that we have moved the contents of this to noir-lang -- should we transfer over this issue?

**Comment by TomAFrench** [comment]
Nope, this was in the context of testing changes to the workflows defined here where we can assume nargo code is a constant but that doesn't hold down in `noir-lang/noir`.
