### ISSUE TITLE
Nightlies broken for UP

### ISSUE THREAD

**Issue by phated** [noir-lang/build-nargo#22]
### Aim

With the UP changes, we now use Nix to build stuff. This will mean that the current way nightlies are built will fail. We need to figure out how to cross-compile with Nix instead of cargo-cross.

### Expected behavior

Nightlies should build.

### Bug

See above.

### To reproduce

1.
2.
3.
4.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
Closing in favour of #23
